# Generated by Django 6.0.1 on 2026-01-07 18:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('category', models.CharField(choices=[('sport', '🏃 Спорт'), ('creative', '🎨 Творчество'), ('study', '📚 Обучение'), ('health', '💊 Здоровье'), ('productivity', '⚡ Продуктивность'), ('other', '📌 Другое')], default='other', max_length=20, verbose_name='Категория')),
                ('duration_days', models.IntegerField(verbose_name='Длительность (дней)')),
                ('difficulty', models.IntegerField(choices=[(1, '⭐ Легко'), (2, '⭐⭐ Средне'), (3, '⭐⭐⭐ Сложно')], default=2, verbose_name='Сложность')),
                ('image', models.ImageField(blank=True, null=True, upload_to='challenge_images/', verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Шаблон челленджа',
                'verbose_name_plural': 'Шаблоны челленджей',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_title', models.CharField(blank=True, max_length=200, verbose_name='Название (кастомное)')),
                ('custom_description', models.TextField(blank=True, verbose_name='Описание (кастомное)')),
                ('custom_category', models.CharField(blank=True, choices=[('sport', '🏃 Спорт'), ('creative', '🎨 Творчество'), ('study', '📚 Обучение'), ('health', '💊 Здоровье'), ('productivity', '⚡ Продуктивность'), ('other', '📌 Другое')], max_length=20, verbose_name='Категория (кастомная)')),
                ('custom_duration', models.IntegerField(blank=True, null=True, verbose_name='Длительность (кастомная)')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата начала')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('completed', 'Завершен'), ('failed', 'Провален'), ('paused', 'Приостановлен')], default='active', max_length=20, verbose_name='Статус')),
                ('current_streak', models.IntegerField(default=0, verbose_name='Текущая серия')),
                ('completed_days', models.IntegerField(default=0, verbose_name='Выполнено дней')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='challenges.challengetemplate', verbose_name='Шаблон')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Челлендж пользователя',
                'verbose_name_plural': 'Челленджи пользователей',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='DailyCheckin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки за день')),
                ('rating', models.IntegerField(blank=True, choices=[(1, '😞 Плохо'), (2, '😐 Нормально'), (3, '🙂 Хорошо'), (4, '😊 Отлично'), (5, '🤩 Супер!')], null=True, verbose_name='Самооценка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время отметки')),
                ('user_challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='challenges.userchallenge', verbose_name='Челлендж')),
            ],
            options={
                'verbose_name': 'Ежедневная отметка',
                'verbose_name_plural': 'Ежедневные отметки',
                'ordering': ['-date'],
                'unique_together': {('user_challenge', 'date')},
            },
        ),
    ]
