# Generated by Django 6.0 on 2026-01-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchallenge',
            name='custom_difficulty',
            field=models.IntegerField(choices=[(1, '⭐ Легко'), (2, '⭐⭐ Средне'), (3, '⭐⭐⭐ Сложно')], default=2, verbose_name='Сложность (кастомная)'),
        ),
    ]
