# Generated by Django 6.0 on 2026-01-19 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_userchallenge_custom_difficulty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('streak', '🔥 Серия дней'), ('completion', '✅ Завершение челленджей'), ('consistency', '📅 Регулярность'), ('variety', '🌈 Разнообразие')], max_length=20, verbose_name='Тип достижения')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('icon', models.CharField(default='🏆', max_length=10, verbose_name='Иконка')),
                ('earned_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата получения')),
                ('progress', models.IntegerField(default=0, verbose_name='Прогресс')),
                ('target', models.IntegerField(default=1, verbose_name='Цель')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения',
                'ordering': ['-earned_date'],
            },
        ),
    ]
